# Generated by Django 6.0.5 on 2026-05-31 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
