# Generated by Django 6.0.5 on 2026-05-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название курса",
                        max_length=255,
                        verbose_name="Название курса",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Введите превью",
                        null=True,
                        upload_to="lms/preview",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "descr",
                    models.TextField(
                        help_text="Введите описание", verbose_name="Описание"
                    ),
                ),
                ("video", models.URLField(blank=True, null=True, verbose_name="Видео")),
            ],
        ),
        migrations.CreateModel(
            name="Сourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название курса",
                        max_length=255,
                        verbose_name="Название курса",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Введите превью",
                        null=True,
                        upload_to="lms/preview",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "descr",
                    models.TextField(
                        help_text="Введите описание", verbose_name="Описание"
                    ),
                ),
            ],
        ),
    ]
