# Generated by Django 6.0.2 on 2026-05-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_course_delete_сourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="descr",
            field=models.TextField(
                blank=True,
                help_text="Введите описание",
                null=True,
                verbose_name="Описание",
            ),
        ),
    ]
