# Generated by Django 6.0.5 on 2026-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="descr",
            field=models.TextField(
                blank=True,
                help_text="Введите описание",
                null=True,
                verbose_name="Описание",
            ),
        ),
    ]
