# Generated by Django 6.0.5 on 2026-05-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0003_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="descr",
            field=models.TextField(
                blank=True,
                help_text="Введите описание",
                null=True,
                verbose_name="Описание",
            ),
        ),
    ]
