# Generated by Django 6.0.5 on 2026-05-26 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0004_alter_lesson_descr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="lesson.course",
                verbose_name="Курс",
            ),
        ),
    ]
