# Generated by Django 6.0.6 on 2026-06-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0004_coursepay"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CoursePay",
        ),
    ]
