# Generated by Django 6.0.6 on 2026-06-14 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0006_lesson_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите лайки",
                related_name="user_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
    ]
